# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Clear Cache Blog
tagline:          'Web, code, miscellaneous'
description:      ''
url:              http://angelitomg.github.io

author:
  name:           'Angelito M. Goulart'
  url:            http://www.angelitomg.com

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/angelitomg/angelitomg.github.io
