# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Angelito Goulart
tagline:          ''
description:      ''
url:              http://angelitomg.github.io

author:
  name:           'Angelito M. Goulart'
  url:            

paginate:         30

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/angelitomg/angelitomg.github.io
